server:
  port: 9111
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

spring:
  application:
    name: myapigateway
  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
      - id: userservice
        uri: http://localhost:9292
        predicates:
        - Path=/user/**
      - id: thirdpartyapp
        uri: http://localhost:9001
        predicates:
        - Path=/news/**          
          
     